version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  hr_processor:
    build: .
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - OLLAMA_HOST=localhost
      - OLLAMA_PORT=11434
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host

  ingestion_api:
    build: .
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    command: python ingestion_api.py
    restart: unless-stopped
    network_mode: host

  streamlit:
    build: .
    depends_on:
      - redis
      - elasticsearch
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: streamlit run ui/streamlit_app.py --server.address=0.0.0.0
    restart: unless-stopped
    network_mode: host

volumes:
  redis_data:
  elasticsearch_data:
